In [19]:
import numpy as np
from scipy.linalg import null_space

def caratheodory(P, w):
    n = P.shape[0]
    d = 1

    if n <= d + 1:
        return P, w 

    unique_points = np.unique(P)
    if len(unique_points) <= d + 1:
        print(f"Not enough unique points: {unique_points}")
        return P, w

    A = []
    for i in range(1, n):
        A.append(P[i] - P[0]) 
    A = np.array(A)

    if A.ndim == 1:
        A = A[np.newaxis, :]

    print("Matrix A:\n", A)
    print("Shape of A:", A.shape)

    v = null_space(A.T)
    print("Null Space:\n", v)

    if v.size == 0:
        raise ValueError("Null space is empty; A may not have sufficient rank.")

    v = v[:, 0]
    v1 = -np.sum(v)
    v = np.append(v1, v)

    alpha = np.inf

    for i in range(n):
        if v[i] > 0:
            alpha = min(alpha, w[i] / v[i])

    S = []
    u = []
    for i in range(n):
        if (w[i] - alpha * v[i]) > 0:
            S.append(P[i])
            u.append(w[i] - alpha * v[i])

    S = np.array(S)
    u = np.array(u)

    if len(P) > d + 1:
        return caratheodory(S, u)
    return S, u

P = np.array([1, 3, 5, 7, 9])
w = np.array([0.25, 0.25, 0.25, 0.15, 0.10])
U = np.sqrt(w)

weightedP = np.multiply(P, U)

x = 3 
v = weightedP * x 

squaredl2Normofv = np.linalg.norm(v)**2
print("Squared L2 Norm of weightedP:", squaredl2Normofv)

try:
    S, u = caratheodory(P, w)
    print("S:", S)
    print("u:", u)
except ValueError as e:
    print(e)


Squared L2 Norm of weightedP: 217.8
Matrix A:
 [[2 4 6 8]]
Shape of A: (1, 4)
Null Space:
 []
Null space is empty; A may not have sufficient rank.


In [20]:
def Caratheodory(P, u, dtype='float64'):
    while 1:
        n = np.count_nonzero(u)
        d = P.shape[1]
        u_non_zero = np.nonzero(u)

        if n <= d + 1:
            return u

        A = P[u_non_zero]
        reduced_vec = np.outer(A[0], np.ones(A.shape[0]-1, dtype = dtype))
        A = A[1:].T - reduced_vec

        _, _, V = np.linalg.svd(A, full_matrices=True)
        v=V[-1]
        v = np.insert(v, [0],   -1 * np.sum(v))

        idx_good_alpha = np.nonzero(v > 0)
        alpha = np.min(u[u_non_zero][idx_good_alpha]/v[idx_good_alpha])

        w = np.zeros(u.shape[0] , dtype = dtype)
        tmp_w = u[u_non_zero] - alpha * v
        tmp_w[np.argmin(tmp_w)] = 0.0
        w[u_non_zero] = tmp_w
        w[u_non_zero][np.argmin(w[u_non_zero] )] = 0
        u = w

P = np.array([[1,2],[2,3],[9,4],[6,5],[5,3],[8,4]]) 
w = np.array([0.25, 0.25, 0.25, 0.15, 0.05,0.05]) 
U = np.sqrt(w)

weightedP = np.multiply(P, U[:, None])

x = [3]
v=[]
for i in range(len(weightedP)):
    v.append(weightedP[i]*x)

squaredl2Normofv=np.linalg.norm(v)**2
print(squaredl2Normofv)

S=P
u = caratheodory(P, w)
# print(S)
print(u)
# u1 = np.sqrt(u)

# weightedS = np.multiply(S, u1[:, None])

# v=[]
# for i in range(len(weightedS)):
#     v.append(weightedS[i]*x)

# squaredl2Normofv=np.linalg.norm(v)**2
# print(squaredl2Normofv)

392.40000000000003
Matrix A:
 [[1 1]
 [8 2]
 [5 3]
 [4 1]
 [7 2]]
Shape of A: (5, 2)
Null Space:
 [[-0.8435024  -0.12986377 -0.32457198]
 [ 0.16829825 -0.36748678 -0.55343662]
 [ 0.40239031  0.07476572  0.03211617]
 [-0.12781503  0.90807758 -0.16270881]
 [-0.28622501 -0.1337687   0.74890276]]
Matrix A:
 [[7 1]
 [4 2]
 [3 0]
 [6 1]]
Shape of A: (4, 2)
Null Space:
 [[-0.40320624 -0.57891418]
 [ 0.27278445 -0.11111542]
 [ 0.86182727 -0.10333639]
 [-0.14236266  0.80114501]]
Matrix A:
 [[7 1]
 [3 0]
 [6 1]]
Shape of A: (3, 2)
Null Space:
 [[-0.6882472 ]
 [ 0.22941573]
 [ 0.6882472 ]]
Matrix A:
 [[7 1]
 [3 0]]
Shape of A: (2, 2)
Null Space:
 []


ValueError: Null space is empty; A may not have sufficient rank.